package fr.ynov.cookieClicker.item;

/**
 * Represents an item in the Cookie Clicker game.
 * Items can generate cookies, have a price, and a name.
 * Some items can increase their cookie gain and price over time.
 *
 * @author BORDES Rémy
 * @version 1.0
 * @since Java 21
 */
public class item {

    /** The price of the item. */
    private int price;

    /** The number of cookies generated by this item. */
    protected int GainCookie;

    /** The name of the item. */
    private String nameItems;

    /**
     * Constructs an {@code item} with the specified parameters.
     *
     * @param price The cost of the item.
     * @param GainCookie The number of cookies generated by the item.
     * @param nameItems The name of the item.
     */
    public item(final int price, final int GainCookie, final String nameItems) {
        this.price = price;
        this.GainCookie = GainCookie;
        this.nameItems = nameItems;
    }

    /**
     * Increases the number of cookies generated by this item.
     * The default increase is 10 cookies.
     */
    public void IncreaseGainCookie() {
        this.GainCookie += 10;
    }

    /**
     * Gets the number of cookies generated by this item.
     *
     * @return The number of cookies generated.
     */
    public int getGainCookie() {
        return GainCookie;
    }

    /**
     * Gets the price of the item.
     *
     * @return The price of the item.
     */
    public int getPrice() {
        return this.price;
    }

    /**
     * Gets the name of the item.
     *
     * @return The item's name.
     */
    public String getName() {
        return this.nameItems;
    }

    /**
     * Increases the price of the item by doubling its current price.
     */
    public void IncreasePrice() {
        this.price *= 2;
    }
}